version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  producer:
    image: python:3.13.3-slim
    volumes:
      - ./producer:/producer
    command: >
      sh -c "pip install redis &&
            python /producer/producer.py"
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"

  consumer:
    image: maven:3.9-eclipse-temurin-21-alpine
    volumes:
      - ./:/app
    command: >
      sh -c "cd /app && mvn clean package && java -jar main/target/main-1.0-SNAPSHOT-all.jar"
    environment:
      REDIS_HOST: "redis"
      SOLUTION_CONSUMER_COUNT: 2